name: Github Pages
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: cargo install wasm-pack --no-default-features
      - name: Build logic
        run: cd logic && wasm-pack build && cd ..
      - name: Build web
        run: cd web && yarn && yarn build && cd ..
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist
